# Generated by Django 2.0.6 on 2018-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horario_inicial', models.DateTimeField(null=True)),
                ('horario_final', models.DateTimeField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos')),
            ],
        ),
    ]
