# Generated by Django 2.0.6 on 2018-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.TextField(null=True),
        ),
    ]
